// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Error {
    /// A description of the error condition
    #[serde(rename = "fault_message")]
    fault_message: Option<String>,
}

impl Error {
    pub fn new() -> Error {
        Error {
            fault_message: None,
        }
    }

    pub fn set_fault_message(&mut self, fault_message: String) {
        self.fault_message = Some(fault_message);
    }

    pub fn with_fault_message(mut self, fault_message: String) -> Error {
        self.fault_message = Some(fault_message);
        self
    }

    pub fn fault_message(&self) -> Option<&String> {
        self.fault_message.as_ref()
    }

    pub fn reset_fault_message(&mut self) {
        self.fault_message = None;
    }
}
