// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git

/// PartialNetworkInterface : Defines a partial network interface structure, used to update the
/// rate limiters for that interface, after microvm start.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PartialNetworkInterface {
    #[serde(rename = "iface_id")]
    iface_id: String,
    #[serde(rename = "rx_rate_limiter")]
    rx_rate_limiter: Option<::models::RateLimiter>,
    #[serde(rename = "tx_rate_limiter")]
    tx_rate_limiter: Option<::models::RateLimiter>,
}

impl PartialNetworkInterface {
    /// Defines a partial network interface structure, used to update the rate limiters for that
    /// interface, after microvm start.
    pub fn new(iface_id: String) -> PartialNetworkInterface {
        PartialNetworkInterface {
            iface_id,
            rx_rate_limiter: None,
            tx_rate_limiter: None,
        }
    }

    pub fn set_iface_id(&mut self, iface_id: String) {
        self.iface_id = iface_id;
    }

    pub fn with_iface_id(mut self, iface_id: String) -> PartialNetworkInterface {
        self.iface_id = iface_id;
        self
    }

    pub fn iface_id(&self) -> &String {
        &self.iface_id
    }

    pub fn set_rx_rate_limiter(&mut self, rx_rate_limiter: ::models::RateLimiter) {
        self.rx_rate_limiter = Some(rx_rate_limiter);
    }

    pub fn with_rx_rate_limiter(
        mut self,
        rx_rate_limiter: ::models::RateLimiter,
    ) -> PartialNetworkInterface {
        self.rx_rate_limiter = Some(rx_rate_limiter);
        self
    }

    pub fn rx_rate_limiter(&self) -> Option<&::models::RateLimiter> {
        self.rx_rate_limiter.as_ref()
    }

    pub fn reset_rx_rate_limiter(&mut self) {
        self.rx_rate_limiter = None;
    }

    pub fn set_tx_rate_limiter(&mut self, tx_rate_limiter: ::models::RateLimiter) {
        self.tx_rate_limiter = Some(tx_rate_limiter);
    }

    pub fn with_tx_rate_limiter(
        mut self,
        tx_rate_limiter: ::models::RateLimiter,
    ) -> PartialNetworkInterface {
        self.tx_rate_limiter = Some(tx_rate_limiter);
        self
    }

    pub fn tx_rate_limiter(&self) -> Option<&::models::RateLimiter> {
        self.tx_rate_limiter.as_ref()
    }

    pub fn reset_tx_rate_limiter(&mut self) {
        self.tx_rate_limiter = None;
    }
}
