// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git

/// RateLimiter : Defines an IO rate limiter with independent bytes/s and ops/s limits. Limits
/// are defined by configuring each of the _bandwidth_ and _ops_ token buckets.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RateLimiter {
    /// Token bucket with bytes as tokens
    #[serde(rename = "bandwidth")]
    bandwidth: Option<::models::TokenBucket>,
    /// Token bucket with operations as tokens
    #[serde(rename = "ops")]
    ops: Option<::models::TokenBucket>,
}

impl RateLimiter {
    /// Defines an IO rate limiter with independent bytes/s and ops/s limits. Limits are defined by
    /// configuring each of the _bandwidth_ and _ops_ token buckets.
    pub fn new() -> RateLimiter {
        RateLimiter {
            bandwidth: None,
            ops: None,
        }
    }

    pub fn set_bandwidth(&mut self, bandwidth: ::models::TokenBucket) {
        self.bandwidth = Some(bandwidth);
    }

    pub fn with_bandwidth(mut self, bandwidth: ::models::TokenBucket) -> RateLimiter {
        self.bandwidth = Some(bandwidth);
        self
    }

    pub fn bandwidth(&self) -> Option<&::models::TokenBucket> {
        self.bandwidth.as_ref()
    }

    pub fn reset_bandwidth(&mut self) {
        self.bandwidth = None;
    }

    pub fn set_ops(&mut self, ops: ::models::TokenBucket) {
        self.ops = Some(ops);
    }

    pub fn with_ops(mut self, ops: ::models::TokenBucket) -> RateLimiter {
        self.ops = Some(ops);
        self
    }

    pub fn ops(&self) -> Option<&::models::TokenBucket> {
        self.ops.as_ref()
    }

    pub fn reset_ops(&mut self) {
        self.ops = None;
    }
}
