// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git

/// BalloonStatsUpdate : Update the statistics polling interval, with the first statistics
/// update scheduled immediately. Statistics cannot be turned on/off after boot.


use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct BalloonStatsUpdate {
    /// Interval in seconds between refreshing statistics.
    #[serde(rename = "stats_polling_interval_s")]
    stats_polling_interval_s: i32,
}

impl BalloonStatsUpdate {
    /// Update the statistics polling interval, with the first statistics update scheduled
    /// immediately. Statistics cannot be turned on/off after boot.
    pub fn new(stats_polling_interval_s: i32) -> BalloonStatsUpdate {
        BalloonStatsUpdate {
            stats_polling_interval_s,
        }
    }

    pub fn set_stats_polling_interval_s(&mut self, stats_polling_interval_s: i32) {
        self.stats_polling_interval_s = stats_polling_interval_s;
    }

    pub fn with_stats_polling_interval_s(
        mut self,
        stats_polling_interval_s: i32,
    ) -> BalloonStatsUpdate {
        self.stats_polling_interval_s = stats_polling_interval_s;
        self
    }

    pub fn stats_polling_interval_s(&self) -> &i32 {
        &self.stats_polling_interval_s
    }
}
