// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git

/// BalloonUpdate : Balloon device descriptor.


use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct BalloonUpdate {
    /// Target balloon size in MiB.
    #[serde(rename = "amount_mib")]
    amount_mib: i32,
}

impl BalloonUpdate {
    /// Balloon device descriptor.
    pub fn new(amount_mib: i32) -> BalloonUpdate {
        BalloonUpdate { amount_mib }
    }

    pub fn set_amount_mib(&mut self, amount_mib: i32) {
        self.amount_mib = amount_mib;
    }

    pub fn with_amount_mib(mut self, amount_mib: i32) -> BalloonUpdate {
        self.amount_mib = amount_mib;
        self
    }

    pub fn amount_mib(&self) -> &i32 {
        &self.amount_mib
    }
}
