// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git


use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct MemoryBackend {
    #[serde(rename = "backend_type")]
    backend_type: String,
    /// Based on 'backend_type' it is either 1) Path to the file that contains the guest memory to
    /// be loaded 2) Path to the UDS where a process is listening for a UFFD initialization control
    /// payload and open file descriptor that it can use to serve this process's guest memory page
    /// faults
    #[serde(rename = "backend_path")]
    backend_path: String,
}

impl MemoryBackend {
    pub fn new(backend_type: String, backend_path: String) -> MemoryBackend {
        MemoryBackend {
            backend_type,
            backend_path,
        }
    }

    pub fn set_backend_type(&mut self, backend_type: String) {
        self.backend_type = backend_type;
    }

    pub fn with_backend_type(mut self, backend_type: String) -> MemoryBackend {
        self.backend_type = backend_type;
        self
    }

    pub fn backend_type(&self) -> &String {
        &self.backend_type
    }

    pub fn set_backend_path(&mut self, backend_path: String) {
        self.backend_path = backend_path;
    }

    pub fn with_backend_path(mut self, backend_path: String) -> MemoryBackend {
        self.backend_path = backend_path;
        self
    }

    pub fn backend_path(&self) -> &String {
        &self.backend_path
    }
}
