// Firecracker API
//
// RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying
// JSON modeled data. The transport medium is a Unix Domain Socket.
//
// OpenAPI spec version: 1.2.0
// Contact: compute-capsule@amazon.com
// Generated by: https://github.com/swagger-api/swagger-codegen.git

/// MmdsContentsObject : Describes the contents of MMDS in JSON format.


use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct MmdsContentsObject {}

impl MmdsContentsObject {
    /// Describes the contents of MMDS in JSON format.
    pub fn new() -> MmdsContentsObject {
        MmdsContentsObject {}
    }
}
